apiVersion: v1
kind: Service
metadata:
  name: hw2-cluster-deployment-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-hw2-cluster-deployment
  ports:
    - name: nodeport
      protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 32354
